# Hugo build configuration for Netlify 

# Default build settings
[build]
  command = "cd themes/docsy && git submodule update -f --init && cd ../.. && hugo"

# "production" environment specific build settings
[build.environment]
  HUGO_BASEURL = "https://elekto.dev"
  HUGO_VERSION = "0.82.0"
  HUGO_ENV = "production"
